- name: pre
  become: yes

  block:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=3600

    # - name: enable GUI
    #   apt: name=ubuntu-desktop

    - name: install user-preferred packages
      apt: name={{ item }}
      with_items:
        - emacs
        - dstat
        - gcc
        - git
        - htop
        - nkf
        - screenfetch
        - tmux
        - vim
        - vim-gnome
        - zsh
